### ISSUE TITLE
bad example

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Dokumentenaustausch#154]
ein Beispiel für eine DocumentReference unter https://simplifier.net/guide/Implementierungsleitfaden-ISiK-Modul-Dokumentenaustausch-Stufe-3/ImplementationGuide-markdown-Datenobjekte-DocumentReference?version=current ist nicht richtig (Serverseitiges Dokument)

        <practiceSetting>            <coding>                <system value="http://snomed.info/sct" />                <code value="408467006" />            </coding>        </practiceSetting>

SNOMED-CT ist an dieser Stelle nicht erlaubt. siehe das entsprechende required-Binding [IHEXDSpracticeSettingCode](https://simplifier.net/resolve?scope=de.basisprofil.r4@1.4.0&filepath=package/ValueSet-1.2.276.0.76.11.37--20190517134631.json).

```[tasklist]
### Tasks
- [ ] PTDATA-711
```

**Comment by alexzautke** [comment]
Fixed by https://github.com/gematik/spec-ISiK-Dokumentenaustausch/pull/160
