### ISSUE TITLE
Umgang mit Updates

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/ISiK-Dokumentenaustausch#22]
Sind Dokumentenupdates (PUT) erlaubt? 
Oder nur POST analog zu MHD/XDS?
Können Dokumente nur mit der "replaces"-Relation aktualisiert werden?
Ist die Interpretation der Relationen optional (analog MHD/XDS?)
Keine Löschung möglich?
Evtl. conditional Update auf identifier erlauben?

**Comment by simoneOnFhir** [comment]
Rückfrage zu Status und Update an IHE: https://chat.fhir.org/#narrow/stream/179223-ihe/topic/MHD.20update.20and.20status

**Comment by simoneOnFhir** [comment]
Enwurf einer Operation: https://simplifier.net/isik-dokumentenaustausch/submit-document

**Comment by simoneOnFhir** [comment]
Termin vom 4.2.: "update" umbenennen in "replace" & Umbenennung der Operation in "provide-document" mit IHE klären
Return Parameter: nur DocumentReference oder ggf sogar nur URL

**Comment by simoneOnFhir** [comment]
Definition einer weiteren Operation zum update von Metadaten (zunächst nur docStatus), aber ausbaufähig...

**Comment by alexzautke** [comment]
Wie unterscheiden die sich von den Meta-Operationen aus der Core-Spec?

**Comment by simoneOnFhir** [comment]
Die Operation ändert die Metadaten eines Dokumentes (DocumentReference) nicht Resource.meta
