### ISSUE TITLE
KDL Binding an eventCode oder an type: klären!

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/ISiK-Dokumentenaustausch#3]
Semantisch wäre type korrekter, wurde aber in XDS an eventCode gebunden. (Weil dort keine Mehrfachcodierung für Type möglich ist)?

**Comment by simoneOnFhir** [comment]
https://wiki.hl7.de/index.php?title=Ihevs:DocumentEntry.eventCodeList

**Comment by simoneOnFhir** [comment]
Konsens vom Meeting am 29.10.2021: KDL ist relevant!

**Comment by simoneOnFhir** [comment]
Entscheidung: 
KDL an type oder event?
Verpflichtend oder optional?

**Comment by andreasghenkel** [comment]
Die gemeinsame Arbeitsgruppe aus IHE Deutschland und der DVMD haben hier immer für die gemeinsame Verfolgung  KDL mit Mapping auf Class. and Type.Code geworben. Die Systemlandschaft in den Krankenhäusern nutzen beides und auch Kombiniert. Ich würde stark dafür werben, dass man beides gemeinsam verfolgt und das man KDL zur Pflicht macht. Nur durch die Sicherstellung einer Pflichtangabe, kann sichergestellt werden, dass die IOP gelebt werden kann.

**Comment by simoneOnFhir** [comment]
Konsens vom 12.11.2021: Binding an type statt eventcode, KDL 1..1 MS, XDS class & type optional
