### ISSUE TITLE
Extraktion Narrative in DocumentReference beschreiben

### ISSUE THREAD

**Issue by alexzautke** [gematik/ISiK-Dokumentenaustausch#39]

**Comment by simoneOnFhir** [comment]
Extranktion beschrieben in https://simplifier.net/guide/isik-dokumentenaustausch/AkteureUndInteraktionen#AkteureUndInteraktionen-Interaktion-Dokumentenbereitstellung Unterkapitel "Hinweise zur Extraktion des Narratives"
