### ISSUE TITLE
Sammlung von UseCases für ITI-66/67

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/ISiK-Dokumentenaustausch#8]
siehe: https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BDOK.5D.20IHE-Profile.20f.C3.BCr.20Dokumenten-Metadaten

**Comment by simoneOnFhir** [comment]
Von Daniel Sänger im Meeting von 4.10.:

Hier drei beispielhafte use cases aus unseren Kundengesprächen:

* Für Bearbeitung von Dokumenten im Rahmen eines Untersuchungsprozesses sollten alle Dokumente zu einer Leistung, Bewegung oder Fall abgefragt und in chronologischer Reihenfolge sortiert angezeigt werden können.

* Für meine tägliche Befundabarbeitung möchte ich alle Dokumente angezeigt bekommen, die z.B. in den letzten 24h neu hinzugekommen sind.

* Als verantwortlicher Arzt der Endoskopie möchte ich alle Untersuchungsbefunde meines Funktionsbereichs sortiert nach Dokumentenstatus angezeigt bekommen, um die Befundfreigabe vorantreiben zu können.

**Comment by simoneOnFhir** [comment]
Rückfrage dazu: Wo im IHE-Kontext würde man die "ausgehende klinische Fragestellung" verorten?

**Comment by andreasghenkel** [comment]
Eine generell gültige Antwort ist mir hierzu nicht bekannt aber ich denke man kann über Beispiele der Doomänenanwendungen hier eine Orientierung finden. In folgender Spezifikation hat man den Umgang mit Assessments beschrieben:
https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_Suppl_ACDC_Rev1-1_TI_2020-03-23.pdf
_(Bei der Rückmeldung habe ich natürlich konkret nach FHIR-Umsetzungen geschaut)_

**Comment by simoneOnFhir** [comment]
Sorry, ich tue mich immer noch schwer mit dem Verständnis des beschriebenen UseCases.
* eine Signalisierungsfunktion bei eingehenden Dokumenten ist im Rahmen des query-basierten Ansatzes von MHD/XDS m.E. nicht umsetzbar. Dazu bräuchte man Messaging oder Subscriptions. 
* Was ist mit "Kontext der Behandlung" gemeint?
* Wer definiert/wo ist ermittelbar, welche weiteren Dokumente im Kontext eines Dokumenttyps/einer Dokumentklasse relevant sind?
* Was ist ein "passendes Fachverfahren"?
* Wo würde man im XDS-Kontext die "verantwortliche Fachabteilung" finden? Die dem Autor zugeordnete Organisation? Custodian des Dokumentes?
* bzgl. "klinsche Fragestellung": IHE-PCC arbeitet mit dem Austausch von strukturierten Questionnaires. Ich fürchte, dass das mit MHD/XDS und unstrukturierten Dokumenten nicht abbildbar ist.

**Comment by simoneOnFhir** [comment]
Den Order-Entry Workflow abzubilden sehe ich derzeit sowohl für MHD/XDS als auch ISiK Stufe 2 out of scope.
Vielleicht ein Thema für Stufe 3...

**Comment by andreasghenkel** [comment]
> Den Order-Entry Workflow abzubilden sehe ich derzeit sowohl für MHD/XDS als auch ISiK Stufe 2 out of scope.
> Vielleicht ein Thema für Stufe 3...

Ich kann verstehen das man Komplexität reduzieren muss. Es sollte nur soweit mitgedacht werden, dass man sich nichts verbaut. 
Ich muss halt die täglich vortragenden Themen im Umgang mit Dokumentenbereitstellungen mit anführen und ich glaube man wird automatisch darauf kommen. 
Das Thema KHZG im FTB 6 sollte dazu genutzt werden dem klinischen Nutzer OrderSets anzubieten, welche auf Basis von Gruppierungen klinischer Fragestellung zur Auswahl der Konsilanforderungen führen. Die Ergebnisse hieraus sollten dann natürlich ebenfalls das Gruppierungsmerkmal mit tragen, auch wenn dieses dann für die Weiterbehandlung/Diagnostik verlassen wird. 
Somit werbe ich schon für eine Aufnahme in die Spezifikation, der Impuls wird aber sicherlich noch aus den anderen AGs kommen.
